### ISSUE TITLE
pinf

### ISSUE THREAD

**Issue by roddy20** [benfry/atomicparsley-hacks#2]
i am not sure, it it the program's bug or I did something wrong
I can read and change stik,rnsd,rndu,rpdu,apID,purd,sfID
but I can do nothing with
moov.trak.mdia.minf.stbl.stsd.mp4a.pinf
moov.trak.mdia.minf.stbl.stsd.avc1.pinf
with movies rented from iTunes
thanks for any help

**Comment by benfry** [comment]
You'd have to check with the authors: https://bitbucket.org/wez/atomicparsley/src/default/ 

This is just a personal fork, I'm not a maintainer or anything like that.
